// 
// Copyright 2022 Clemens Cords
// Created on 20.05.22 by clem (mail@clemens-cords.com)
//

#pragma once

#include <SDL2/SDL_gamecontroller.h>
#include <SDL2/SDL_keycode.h>

namespace ts
{
    namespace detail
    {
        constexpr int64_t CONTROLLER_OFFSET = 65536;
    }

    //
    enum KeyOrButton
    {
        // keyboard keys

        NUM_0 = SDLK_0,
        NUM_1 = SDLK_1,
        NUM_2 = SDLK_2,
        NUM_3 = SDLK_3,
        NUM_4 = SDLK_4,
        NUM_5 = SDLK_5,
        NUM_6 = SDLK_6,
        NUM_7 = SDLK_7,
        NUM_8 = SDLK_8,
        NUM_9 = SDLK_9,

        A = SDLK_a,
        B = SDLK_b,
        C = SDLK_c,
        D = SDLK_d,
        E = SDLK_e,
        F = SDLK_f,
        G = SDLK_g,
        H = SDLK_h,
        I = SDLK_i,
        J = SDLK_j,
        K = SDLK_k,
        L = SDLK_l,
        M = SDLK_m,
        N = SDLK_n,
        O = SDLK_o,
        P = SDLK_p,
        Q = SDLK_q,
        R = SDLK_r,
        S = SDLK_s,
        T = SDLK_t,
        U = SDLK_u,
        V = SDLK_v,
        W = SDLK_w,
        X = SDLK_x,
        Y = SDLK_y,
        Z = SDLK_z,

        ALT = SDLK_LALT,
        RIGHT_ALT = SDLK_RALT,

        CTRL = SDLK_LCTRL,
        RIGHT_CTRL = SDLK_RCTRL,
        CAPS = SDLK_CAPSLOCK,

        SHIFT = SDLK_LSHIFT,
        RIGHT_SHIFT = SDLK_RSHIFT,

        BRACKET_LEFT = SDLK_LEFTBRACKET,
        BRACKET_RIGHT = SDLK_RIGHTBRACKET,

        SLASH = SDLK_SLASH,
        BACKSLASH = SDLK_BACKSLASH,

        UP = SDLK_UP,
        DOWN = SDLK_DOWN,
        LEFT = SDLK_LEFT,
        RIGHT = SDLK_RIGHT,

        RETURN = SDLK_RETURN,
        ESCAPE = SDLK_ESCAPE,
        BACKSPACE = SDLK_BACKSPACE,
        TAB = SDLK_TAB,
        SPACE = SDLK_SPACE,
        SDLK_EXCLAIM,
        SDLK_QUOTEDBL,

        HASH = SDLK_HASH,
        PERCENT = SDLK_PERCENT,
        DOLLAR = SDLK_DOLLAR,
        AND = SDLK_AMPERSAND,
        QUOTE = SDLK_QUOTE,

        LEFT_PARENTHESIS = SDLK_LEFTPAREN,
        RIGHT_PARENTHESIS= SDLK_RIGHTPAREN,

        ASTERISK = SDLK_ASTERISK,
        PLUS = SDLK_PLUS,
        MINUS = SDLK_MINUS,
        UNDERSCORE = SDLK_UNDERSCORE,

        COMMA = SDLK_COMMA,
        PERIOD = SDLK_PERIOD,
        SEMICOLON = SDLK_SEMICOLON,
        COLON = SDLK_COLON,

        LESS_THAN = SDLK_LESS,
        GREATER_THAN = SDLK_GREATER,

        EQUALS = SDLK_EQUALS,
        CIRCUMFLEX = SDLK_CARET,

        EXCLAMATION_MARK = SDLK_EXCLAIM,
        QUESTION_MARK = SDLK_QUESTION,

        F1 = SDLK_F1,
        F2 = SDLK_F2,
        F3 = SDLK_F3,
        F4 = SDLK_F4,
        F5 = SDLK_F5,
        F6 = SDLK_F6,
        F7 = SDLK_F7,
        F8 = SDLK_F8,
        F9 = SDLK_F9,
        F10 = SDLK_F10,
        F11 = SDLK_F11,
        F12 = SDLK_F12,

        AUDIO_MUTE = SDLK_AUDIOMUTE,
        AUDIO_STOP = SDLK_AUDIOSTOP,
        AUDIO_PLAY = SDLK_AUDIOPLAY,
        AUDIO_NEXT = SDLK_AUDIONEXT,
        AUDIO_PREV = SDLK_AUDIOPREV,
        VOLUME_UP = SDLK_VOLUMEUP,
        VOLUME_DOWN = SDLK_VOLUMEDOWN,

        INSERT = SDLK_INSERT,
        PRINTSCREEN = SDLK_PRINTSCREEN,
        DELETE = SDLK_DELETE,

        // controller buttons

        CONTROLLER_BUTTON_UNKNOWN = SDL_CONTROLLER_BUTTON_INVALID + detail::CONTROLLER_OFFSET,

        CONTROLLER_BUTTON_A = SDL_CONTROLLER_BUTTON_A + detail::CONTROLLER_OFFSET,
        CONTROLLER_BUTTON_B = SDL_CONTROLLER_BUTTON_B + detail::CONTROLLER_OFFSET,
        CONTROLLER_BUTTON_X = SDL_CONTROLLER_BUTTON_X + detail::CONTROLLER_OFFSET,
        CONTROLLER_BUTTON_Y = SDL_CONTROLLER_BUTTON_Y + detail::CONTROLLER_OFFSET,

        CONTROLLER_LEFTSTICK_PRESS = SDL_CONTROLLER_BUTTON_LEFTSTICK + detail::CONTROLLER_OFFSET,
        CONTROLLER_RIGHTSTICK_PRESS = SDL_CONTROLLER_BUTTON_RIGHTSTICK + detail::CONTROLLER_OFFSET,
        CONTROLLER_LEFTSHOULDER = SDL_CONTROLLER_BUTTON_LEFTSHOULDER + detail::CONTROLLER_OFFSET,
        CONTROLLER_RIGHTSHOULDER = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER + detail::CONTROLLER_OFFSET,

        CONTROLLER_DPAD_UP = SDL_CONTROLLER_BUTTON_DPAD_UP + detail::CONTROLLER_OFFSET,
        CONTROLLER_DPAD_DOWN = SDL_CONTROLLER_BUTTON_DPAD_DOWN + detail::CONTROLLER_OFFSET,
        CONTROLLER_DPAD_LEFT = SDL_CONTROLLER_BUTTON_DPAD_LEFT + detail::CONTROLLER_OFFSET,
        CONTROLLER_DPAD_RIGHT = SDL_CONTROLLER_BUTTON_DPAD_RIGHT + detail::CONTROLLER_OFFSET,

        CONTROLLER_SELECT = SDL_CONTROLLER_BUTTON_BACK + detail::CONTROLLER_OFFSET, //TODO verify this
        CONTROLLER_START = SDL_CONTROLLER_BUTTON_START + detail::CONTROLLER_OFFSET,

        CONTROLLER_GUIDE = SDL_CONTROLLER_BUTTON_GUIDE + detail::CONTROLLER_OFFSET,
        CONTROLLER_MAX = SDL_CONTROLLER_BUTTON_MAX + detail::CONTROLLER_OFFSET,

        CONTROLLER_XBOX_X_SHARE = SDL_CONTROLLER_BUTTON_MISC1 + detail::CONTROLLER_OFFSET,
        CONTROLLER_PS5_MIC = SDL_CONTROLLER_BUTTON_MISC1 + detail::CONTROLLER_OFFSET,
        CONTROLLER_SWITCH_CAPTURE = SDL_CONTROLLER_BUTTON_MISC1 + detail::CONTROLLER_OFFSET,

        CONTROLLER_PADDLE_01 = SDL_CONTROLLER_BUTTON_PADDLE1 + detail::CONTROLLER_OFFSET,
        CONTROLLER_PADDLE_02 = SDL_CONTROLLER_BUTTON_PADDLE2 + detail::CONTROLLER_OFFSET,
        CONTROLLER_PADDLE_03 = SDL_CONTROLLER_BUTTON_PADDLE3 + detail::CONTROLLER_OFFSET,
        CONTROLLER_PADDLE_04 = SDL_CONTROLLER_BUTTON_PADDLE4 + detail::CONTROLLER_OFFSET,

        CONTROLLER_PS5_TOUCHPAD = SDL_CONTROLLER_BUTTON_TOUCHPAD + detail::CONTROLLER_OFFSET,
    };
}